name: dart
description: An absolute bare-bones web app.
version: 1.0.0
author: Brett Morgan 

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
