name: dart_custom_runtime
description: Dart custom runtime for Google App Engine.
version: 1.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http_server: ^0.9.8+1

dev_dependencies:
  pedantic: '1.1.0'